openapi: 3.0.0
info:
  title: Products
  version: 1
paths:
  /api/products:
    get:
      summary: Get all products
      operationId: getProducts
      responses:
        "200":
          description: OK
    post:
      summary: Create a new product
      operationId: createProduct
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        "201":
          description: Created
  /api/products/{id}:
    get:
      summary: Get a product by ID
      operationId: findProductById
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: OK
    put:
      summary: Update a product by ID
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        "200":
          description: OK
    delete:
      summary: Delete a product by ID
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "204":
          description: No Content
definitions:
  ProductInput:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      code:
        type: string
      price:
        type: number
      status:
        type: boolean
      stock:
        type: number
      category:
        type: string
      thumbnail:
        type: array
        items:
          type: string
  AddProductToCartInput:
    type: object
    properties:
      quantity:
        type: integer
